services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'thulasi_stores'
      MYSQL_USER: 'thulasi_user'
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD:?err}
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD:?err}
    expose:
      - 3306
    volumes:
      - db-mysql:/var/lib/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend_fastapi
    depends_on:
      - db
    restart: always
    environment:
      APP_ENV: 'PROD'
      APP_PORT: 8000
      APP_HOST: 'localhost'
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_NAME: 'thulasi_stores'
      DB_USER: 'thulasi_user'
      DB_PASSWORD: ${ENV_MYSQL_PASSWORD:?err}
      DB_POOL_SIZE: 7
      SECRET_KEY: ${ENV_SECRET_KEY:?err}
    expose:
      - 8000

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
      - backend
    restart: always

volumes:
  db-mysql: