services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'thulasi_stores'
      MYSQL_USER: 'thulasi_user'
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD:?err}
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD:?err}
    expose:
      - 3306
    volumes:
      - db-mysql:/var/lib/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend_fastapi
    depends_on:
      - db
    restart: always
    environment:
      APP_ENV: 'PROD'
      APP_PORT: 8000
      APP_HOST: 'localhost'
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_NAME: 'thulasi_stores'
      DB_USER: 'thulasi_user'
      DB_PASSWORD: ${ENV_MYSQL_PASSWORD:?err}
      DB_POOL_SIZE: 7
      SECRET_KEY: ${ENV_SECRET_KEY:?err}
    expose:
      - 8000

  grafana:
    image: grafana/grafana:7.5.7
    expose: 
      - 3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - db
    environment:
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_PROTOCOL: http
      GF_SERVER_DOMAIN: "localhost:80"
      GF_SERVER_ROOT_URL: "http://localhost:80/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
      - backend
      - grafana
    restart: always

volumes:
  db-mysql:
  grafana-data: